import type { MansionProperty } from "../types/property.types";

export const mansionProperties: MansionProperty[] = [
  {
    id: 1,
    type: "mansion",
    image: "/image-8.png",
    price: "299",
    title: "第一ベンチャーハイツ大津",
    description: "滋賀県大津市の中古マンション。JR東海道本線の大津駅から徒歩15分の立地。",
    details: {
      location: "滋賀県大津市",
      access: "JR東海道本線 大津駅 徒歩15分",
      buildingType: "中古マンション",
      floor: "3階建て",
      rooms: "3DK",
      area: "58.32㎡",
      year: "1985年3月",
    },
  },
  {
    id: 2,
    type: "mansion",
    image: "/image-12.png",
    price: "850",
    title: "ビッグウィングマンション東大阪",
    description: "大阪府東大阪市の中古マンション。近鉄奈良線の河内永和駅から徒歩8分。",
    details: {
      location: "大阪府東大阪市",
      access: "近鉄奈良線 河内永和駅 徒歩8分",
      buildingType: "中古マンション",
      floor: "7階建て",
      rooms: "3LDK",
      area: "65.45㎡",
      year: "1992年8月",
    },
  },
  {
    id: 3,
    type: "mansion",
    image: "/image-13.png",
    price: "900",
    title: "ダイアパレス東神戸",
    description: "兵庫県神戸市の中古マンション。JR東海道本線の住吉駅から徒歩12分。",
    details: {
      location: "兵庫県神戸市",
      access: "JR東海道本線 住吉駅 徒歩12分",
      buildingType: "中古マンション",
      floor: "8階建て",
      rooms: "2LDK",
      area: "52.18㎡",
      year: "1988年11月",
    },
  },
  {
    id: 4,
    type: "mansion",
    image: "/image-14.png",
    price: "980",
    title: "ハッピー東雲マンション",
    description: "東京都江東区の中古マンション。ゆりかもめ東雲駅から徒歩5分の好立地。",
    details: {
      location: "東京都江東区",
      access: "ゆりかもめ 東雲駅 徒歩5分",
      buildingType: "中古マンション",
      floor: "12階建て",
      rooms: "1LDK",
      area: "45.32㎡",
      year: "1995年3月",
    },
  },
  {
    id: 5,
    type: "mansion",
    image: "/image-15.png",
    price: "1,050",
    title: "日野ハイム大阪南港",
    description: "大阪府大阪市の中古マンション。ニュートラム南港ポートタウン線から徒歩3分。",
    details: {
      location: "大阪府大阪市",
      access: "ニュートラム 南港ポートタウン線 徒歩3分",
      buildingType: "中古マンション",
      floor: "15階建て",
      rooms: "3LDK",
      area: "78.45㎡",
      year: "1998年7月",
    },
  },
  {
    id: 6,
    type: "mansion",
    image: "/image-16.png",
    price: "1,140",
    title: "日野ハイム大阪南港2号棟",
    description: "大阪府大阪市の中古マンション。ニュートラム南港ポートタウン線から徒歩2分。",
    details: {
      location: "大阪府大阪市",
      access: "ニュートラム 南港ポートタウン線 徒歩2分",
      buildingType: "中古マンション",
      floor: "15階建て",
      rooms: "3LDK",
      area: "82.15㎡",
      year: "1999年3月",
    },
  },
  {
    id: 7,
    type: "mansion",
    image: "/image-17.png",
    price: "1,400",
    title: "サンマンション大津本町",
    description: "滋賀県大津市の中古マンション。JR東海道本線の大津駅から徒歩8分。",
    details: {
      location: "滋賀県大津市",
      access: "JR東海道本線 大津駅 徒歩8分",
      buildingType: "中古マンション",
      floor: "10階建て",
      rooms: "4LDK",
      area: "95.28㎡",
      year: "2001年5月",
    },
  },
  {
    id: 8,
    type: "mansion",
    image: "/image-18.png",
    price: "1,670",
    title: "八幡市中央マンション",
    description: "京都府八幡市の中古マンション。京阪本線の八幡市駅から徒歩7分。",
    details: {
      location: "京都府八幡市",
      access: "京阪本線 八幡市駅 徒歩7分",
      buildingType: "中古マンション",
      floor: "11階建て",
      rooms: "3LDK",
      area: "88.42㎡",
      year: "2003年9月",
    },
  },
];
