import { type NextRequest, NextResponse } from "next/server";

// 郵便番号APIのレスポンス型
interface PostcodeItem {
  prefecture: string;
  city: string;
  suburb?: string;
}

// 市区町村データの型
interface CityItem {
  city: string;
  suburb: string;
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const prefecture = searchParams.get("prefecture");

  if (!prefecture) {
    return NextResponse.json({ error: "都道府県が指定されていません" }, { status: 400 });
  }

  try {
    // 都道府県名で検索するAPIを呼び出し
    const response = await fetch(
      `https://postcode.teraren.com/postcodes.json?s=${encodeURIComponent(prefecture)}&per=100`,
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    if (!response.ok) {
      throw new Error(`API request failed: ${response.status}`);
    }

    const data: PostcodeItem[] = await response.json();

    // レスポンスが配列の場合
    if (Array.isArray(data) && data.length > 0) {
      // 都道府県名でフィルタリングし、市区町村の一意なリストを作成
      const cities: CityItem[] = data
        .filter((item) => item.prefecture === prefecture)
        .map((item) => ({
          city: item.city,
          suburb: item.suburb || "",
        }))
        .filter((item, index, self) => index === self.findIndex((t) => t.city === item.city));

      // 外部APIから十分なデータが取得できない場合は、デフォルトデータとマージ
      if (cities.length < 10) {
        const defaultCities = getDefaultCitiesForPrefecture(prefecture);
        const mergedCities = [...cities, ...defaultCities].filter(
          (item, index, self) => index === self.findIndex((t) => t.city === item.city)
        );
        return NextResponse.json({
          success: true,
          data: mergedCities,
        });
      }

      return NextResponse.json({
        success: true,
        data: cities,
      });
    }
    // 検索APIが動作しない場合、都道府県に応じたデフォルトの市区町村を返す
    const defaultCities = getDefaultCitiesForPrefecture(prefecture);
    return NextResponse.json({
      success: true,
      data: defaultCities,
    });
  } catch (error) {
    console.error("市区町村API エラー:", error);
    // エラーの場合もデフォルトの市区町村を返す
    const defaultCities = getDefaultCitiesForPrefecture(prefecture);
    return NextResponse.json({
      success: true,
      data: defaultCities,
    });
  }
}

// 都道府県に応じたデフォルトの市区町村を返す関数
function getDefaultCitiesForPrefecture(
  prefecture: string
): Array<{ city: string; suburb: string }> {
  const defaultCities: Record<string, Array<{ city: string; suburb: string }>> = {
    北海道: [
      { city: "札幌市", suburb: "札幌" },
      { city: "函館市", suburb: "函館" },
      { city: "小樽市", suburb: "小樽" },
      { city: "旭川市", suburb: "旭川" },
      { city: "室蘭市", suburb: "室蘭" },
      { city: "釧路市", suburb: "釧路" },
      { city: "帯広市", suburb: "帯広" },
      { city: "北見市", suburb: "北見" },
      { city: "苫小牧市", suburb: "苫小牧" },
      { city: "江別市", suburb: "江別" },
    ],
    青森県: [
      { city: "青森市", suburb: "青森" },
      { city: "弘前市", suburb: "弘前" },
      { city: "八戸市", suburb: "八戸" },
      { city: "黒石市", suburb: "黒石" },
      { city: "五所川原市", suburb: "五所川原" },
      { city: "十和田市", suburb: "十和田" },
      { city: "三沢市", suburb: "三沢" },
      { city: "むつ市", suburb: "むつ" },
      { city: "つがる市", suburb: "つがる" },
      { city: "平川市", suburb: "平川" },
    ],
    岩手県: [
      { city: "盛岡市", suburb: "盛岡" },
      { city: "宮古市", suburb: "宮古" },
      { city: "大船渡市", suburb: "大船渡" },
      { city: "花巻市", suburb: "花巻" },
      { city: "北上市", suburb: "北上" },
      { city: "久慈市", suburb: "久慈" },
      { city: "遠野市", suburb: "遠野" },
      { city: "一関市", suburb: "一関" },
      { city: "陸前高田市", suburb: "陸前高田" },
      { city: "釜石市", suburb: "釜石" },
    ],
    宮城県: [
      { city: "仙台市", suburb: "仙台" },
      { city: "石巻市", suburb: "石巻" },
      { city: "塩竈市", suburb: "塩竈" },
      { city: "気仙沼市", suburb: "気仙沼" },
      { city: "白石市", suburb: "白石" },
      { city: "名取市", suburb: "名取" },
      { city: "角田市", suburb: "角田" },
      { city: "多賀城市", suburb: "多賀城" },
      { city: "岩沼市", suburb: "岩沼" },
      { city: "登米市", suburb: "登米" },
    ],
    秋田県: [
      { city: "秋田市", suburb: "秋田" },
      { city: "能代市", suburb: "能代" },
      { city: "横手市", suburb: "横手" },
      { city: "大館市", suburb: "大館" },
      { city: "男鹿市", suburb: "男鹿" },
      { city: "湯沢市", suburb: "湯沢" },
      { city: "鹿角市", suburb: "鹿角" },
      { city: "由利本荘市", suburb: "由利本荘" },
      { city: "潟上市", suburb: "潟上" },
      { city: "大仙市", suburb: "大仙" },
    ],
    山形県: [
      { city: "山形市", suburb: "山形" },
      { city: "米沢市", suburb: "米沢" },
      { city: "鶴岡市", suburb: "鶴岡" },
      { city: "酒田市", suburb: "酒田" },
      { city: "新庄市", suburb: "新庄" },
      { city: "寒河江市", suburb: "寒河江" },
      { city: "上山市", suburb: "上山" },
      { city: "村山市", suburb: "村山" },
      { city: "長井市", suburb: "長井" },
      { city: "天童市", suburb: "天童" },
    ],
    福島県: [
      { city: "福島市", suburb: "福島" },
      { city: "会津若松市", suburb: "会津若松" },
      { city: "郡山市", suburb: "郡山" },
      { city: "いわき市", suburb: "いわき" },
      { city: "白河市", suburb: "白河" },
      { city: "須賀川市", suburb: "須賀川" },
      { city: "喜多方市", suburb: "喜多方" },
      { city: "相馬市", suburb: "相馬" },
      { city: "二本松市", suburb: "二本松" },
      { city: "田村市", suburb: "田村" },
    ],
    茨城県: [
      { city: "水戸市", suburb: "水戸" },
      { city: "日立市", suburb: "日立" },
      { city: "土浦市", suburb: "土浦" },
      { city: "古河市", suburb: "古河" },
      { city: "石岡市", suburb: "石岡" },
      { city: "結城市", suburb: "結城" },
      { city: "龍ケ崎市", suburb: "龍ケ崎" },
      { city: "下妻市", suburb: "下妻" },
      { city: "常総市", suburb: "常総" },
      { city: "常陸太田市", suburb: "常陸太田" },
    ],
    栃木県: [
      { city: "宇都宮市", suburb: "宇都宮" },
      { city: "足利市", suburb: "足利" },
      { city: "栃木市", suburb: "栃木" },
      { city: "佐野市", suburb: "佐野" },
      { city: "鹿沼市", suburb: "鹿沼" },
      { city: "日光市", suburb: "日光" },
      { city: "小山市", suburb: "小山" },
      { city: "真岡市", suburb: "真岡" },
      { city: "大田原市", suburb: "大田原" },
      { city: "矢板市", suburb: "矢板" },
    ],
    群馬県: [
      { city: "前橋市", suburb: "前橋" },
      { city: "高崎市", suburb: "高崎" },
      { city: "桐生市", suburb: "桐生" },
      { city: "伊勢崎市", suburb: "伊勢崎" },
      { city: "太田市", suburb: "太田" },
      { city: "沼田市", suburb: "沼田" },
      { city: "館林市", suburb: "館林" },
      { city: "渋川市", suburb: "渋川" },
      { city: "藤岡市", suburb: "藤岡" },
      { city: "富岡市", suburb: "富岡" },
    ],
    埼玉県: [
      { city: "さいたま市", suburb: "さいたま" },
      { city: "川越市", suburb: "川越" },
      { city: "熊谷市", suburb: "熊谷" },
      { city: "川口市", suburb: "川口" },
      { city: "行田市", suburb: "行田" },
      { city: "秩父市", suburb: "秩父" },
      { city: "所沢市", suburb: "所沢" },
      { city: "飯能市", suburb: "飯能" },
      { city: "加須市", suburb: "加須" },
      { city: "本庄市", suburb: "本庄" },
    ],
    千葉県: [
      { city: "千葉市", suburb: "千葉" },
      { city: "銚子市", suburb: "銚子" },
      { city: "市川市", suburb: "市川" },
      { city: "船橋市", suburb: "船橋" },
      { city: "館山市", suburb: "館山" },
      { city: "木更津市", suburb: "木更津" },
      { city: "松戸市", suburb: "松戸" },
      { city: "野田市", suburb: "野田" },
      { city: "茂原市", suburb: "茂原" },
      { city: "成田市", suburb: "成田" },
    ],
    東京都: [
      { city: "千代田区", suburb: "千代田" },
      { city: "中央区", suburb: "中央" },
      { city: "港区", suburb: "港" },
      { city: "新宿区", suburb: "新宿" },
      { city: "文京区", suburb: "文京" },
      { city: "台東区", suburb: "台東" },
      { city: "墨田区", suburb: "墨田" },
      { city: "江東区", suburb: "江東" },
      { city: "品川区", suburb: "品川" },
      { city: "目黒区", suburb: "目黒" },
      { city: "大田区", suburb: "大田" },
      { city: "世田谷区", suburb: "世田谷" },
      { city: "渋谷区", suburb: "渋谷" },
      { city: "中野区", suburb: "中野" },
      { city: "杉並区", suburb: "杉並" },
      { city: "豊島区", suburb: "豊島" },
      { city: "北区", suburb: "北" },
      { city: "荒川区", suburb: "荒川" },
      { city: "板橋区", suburb: "板橋" },
      { city: "練馬区", suburb: "練馬" },
      { city: "足立区", suburb: "足立" },
      { city: "葛飾区", suburb: "葛飾" },
      { city: "江戸川区", suburb: "江戸川" },
    ],
    神奈川県: [
      { city: "横浜市", suburb: "横浜" },
      { city: "川崎市", suburb: "川崎" },
      { city: "相模原市", suburb: "相模原" },
      { city: "横須賀市", suburb: "横須賀" },
      { city: "平塚市", suburb: "平塚" },
      { city: "鎌倉市", suburb: "鎌倉" },
      { city: "藤沢市", suburb: "藤沢" },
      { city: "茅ヶ崎市", suburb: "茅ヶ崎" },
      { city: "逗子市", suburb: "逗子" },
      { city: "三浦市", suburb: "三浦" },
    ],
    新潟県: [
      { city: "新潟市", suburb: "新潟" },
      { city: "長岡市", suburb: "長岡" },
      { city: "三条市", suburb: "三条" },
      { city: "柏崎市", suburb: "柏崎" },
      { city: "新発田市", suburb: "新発田" },
      { city: "小千谷市", suburb: "小千谷" },
      { city: "加茂市", suburb: "加茂" },
      { city: "十日町市", suburb: "十日町" },
      { city: "見附市", suburb: "見附" },
      { city: "村上市", suburb: "村上" },
    ],
    富山県: [
      { city: "富山市", suburb: "富山" },
      { city: "高岡市", suburb: "高岡" },
      { city: "魚津市", suburb: "魚津" },
      { city: "氷見市", suburb: "氷見" },
      { city: "滑川市", suburb: "滑川" },
      { city: "黒部市", suburb: "黒部" },
      { city: "砺波市", suburb: "砺波" },
      { city: "小矢部市", suburb: "小矢部" },
      { city: "南砺市", suburb: "南砺" },
      { city: "射水市", suburb: "射水" },
    ],
    石川県: [
      { city: "金沢市", suburb: "金沢" },
      { city: "七尾市", suburb: "七尾" },
      { city: "小松市", suburb: "小松" },
      { city: "輪島市", suburb: "輪島" },
      { city: "珠洲市", suburb: "珠洲" },
      { city: "加賀市", suburb: "加賀" },
      { city: "羽咋市", suburb: "羽咋" },
      { city: "かほく市", suburb: "かほく" },
      { city: "白山市", suburb: "白山" },
      { city: "能美市", suburb: "能美" },
    ],
    福井県: [
      { city: "福井市", suburb: "福井" },
      { city: "敦賀市", suburb: "敦賀" },
      { city: "小浜市", suburb: "小浜" },
      { city: "大野市", suburb: "大野" },
      { city: "勝山市", suburb: "勝山" },
      { city: "鯖江市", suburb: "鯖江" },
      { city: "あわら市", suburb: "あわら" },
      { city: "越前市", suburb: "越前" },
      { city: "坂井市", suburb: "坂井" },
      { city: "永平寺町", suburb: "永平寺" },
    ],
    山梨県: [
      { city: "甲府市", suburb: "甲府" },
      { city: "富士吉田市", suburb: "富士吉田" },
      { city: "都留市", suburb: "都留" },
      { city: "山梨市", suburb: "山梨" },
      { city: "大月市", suburb: "大月" },
      { city: "韮崎市", suburb: "韮崎" },
      { city: "南アルプス市", suburb: "南アルプス" },
      { city: "北杜市", suburb: "北杜" },
      { city: "甲斐市", suburb: "甲斐" },
      { city: "笛吹市", suburb: "笛吹" },
    ],
    長野県: [
      { city: "長野市", suburb: "長野" },
      { city: "松本市", suburb: "松本" },
      { city: "上田市", suburb: "上田" },
      { city: "岡谷市", suburb: "岡谷" },
      { city: "飯田市", suburb: "飯田" },
      { city: "諏訪市", suburb: "諏訪" },
      { city: "須坂市", suburb: "須坂" },
      { city: "小諸市", suburb: "小諸" },
      { city: "伊那市", suburb: "伊那" },
      { city: "駒ヶ根市", suburb: "駒ヶ根" },
    ],
    岐阜県: [
      { city: "岐阜市", suburb: "岐阜" },
      { city: "大垣市", suburb: "大垣" },
      { city: "高山市", suburb: "高山" },
      { city: "多治見市", suburb: "多治見" },
      { city: "関市", suburb: "関" },
      { city: "中津川市", suburb: "中津川" },
      { city: "美濃市", suburb: "美濃" },
      { city: "瑞浪市", suburb: "瑞浪" },
      { city: "羽島市", suburb: "羽島" },
      { city: "恵那市", suburb: "恵那" },
    ],
    静岡県: [
      { city: "静岡市", suburb: "静岡" },
      { city: "浜松市", suburb: "浜松" },
      { city: "沼津市", suburb: "沼津" },
      { city: "熱海市", suburb: "熱海" },
      { city: "三島市", suburb: "三島" },
      { city: "富士宮市", suburb: "富士宮" },
      { city: "伊東市", suburb: "伊東" },
      { city: "島田市", suburb: "島田" },
      { city: "富士市", suburb: "富士" },
      { city: "磐田市", suburb: "磐田" },
    ],
    愛知県: [
      { city: "名古屋市", suburb: "名古屋" },
      { city: "豊橋市", suburb: "豊橋" },
      { city: "岡崎市", suburb: "岡崎" },
      { city: "一宮市", suburb: "一宮" },
      { city: "瀬戸市", suburb: "瀬戸" },
      { city: "半田市", suburb: "半田" },
      { city: "春日井市", suburb: "春日井" },
      { city: "豊川市", suburb: "豊川" },
      { city: "津島市", suburb: "津島" },
      { city: "碧南市", suburb: "碧南" },
    ],
    三重県: [
      { city: "津市", suburb: "津" },
      { city: "四日市市", suburb: "四日市" },
      { city: "伊勢市", suburb: "伊勢" },
      { city: "松阪市", suburb: "松阪" },
      { city: "桑名市", suburb: "桑名" },
      { city: "鈴鹿市", suburb: "鈴鹿" },
      { city: "名張市", suburb: "名張" },
      { city: "尾鷲市", suburb: "尾鷲" },
      { city: "亀山市", suburb: "亀山" },
      { city: "鳥羽市", suburb: "鳥羽" },
    ],
    滋賀県: [
      { city: "大津市", suburb: "大津" },
      { city: "彦根市", suburb: "彦根" },
      { city: "長浜市", suburb: "長浜" },
      { city: "近江八幡市", suburb: "近江八幡" },
      { city: "草津市", suburb: "草津" },
      { city: "守山市", suburb: "守山" },
      { city: "栗東市", suburb: "栗東" },
      { city: "甲賀市", suburb: "甲賀" },
      { city: "野洲市", suburb: "野洲" },
      { city: "湖南市", suburb: "湖南" },
    ],
    京都府: [
      { city: "京都市", suburb: "京都" },
      { city: "福知山市", suburb: "福知山" },
      { city: "舞鶴市", suburb: "舞鶴" },
      { city: "綾部市", suburb: "綾部" },
      { city: "宇治市", suburb: "宇治" },
      { city: "宮津市", suburb: "宮津" },
      { city: "亀岡市", suburb: "亀岡" },
      { city: "城陽市", suburb: "城陽" },
      { city: "向日市", suburb: "向日" },
      { city: "長岡京市", suburb: "長岡京" },
    ],
    大阪府: [
      { city: "大阪市", suburb: "大阪" },
      { city: "堺市", suburb: "堺" },
      { city: "東大阪市", suburb: "東大阪" },
      { city: "豊中市", suburb: "豊中" },
      { city: "吹田市", suburb: "吹田" },
      { city: "高槻市", suburb: "高槻" },
      { city: "茨木市", suburb: "茨木" },
      { city: "八尾市", suburb: "八尾" },
      { city: "泉佐野市", suburb: "泉佐野" },
      { city: "寝屋川市", suburb: "寝屋川" },
    ],
    兵庫県: [
      { city: "神戸市", suburb: "神戸" },
      { city: "姫路市", suburb: "姫路" },
      { city: "尼崎市", suburb: "尼崎" },
      { city: "明石市", suburb: "明石" },
      { city: "西宮市", suburb: "西宮" },
      { city: "洲本市", suburb: "洲本" },
      { city: "芦屋市", suburb: "芦屋" },
      { city: "伊丹市", suburb: "伊丹" },
      { city: "相生市", suburb: "相生" },
      { city: "豊岡市", suburb: "豊岡" },
    ],
    奈良県: [
      { city: "奈良市", suburb: "奈良" },
      { city: "大和高田市", suburb: "大和高田" },
      { city: "大和郡山市", suburb: "大和郡山" },
      { city: "天理市", suburb: "天理" },
      { city: "橿原市", suburb: "橿原" },
      { city: "桜井市", suburb: "桜井" },
      { city: "五條市", suburb: "五條" },
      { city: "御所市", suburb: "御所" },
      { city: "生駒市", suburb: "生駒" },
      { city: "香芝市", suburb: "香芝" },
    ],
    和歌山県: [
      { city: "和歌山市", suburb: "和歌山" },
      { city: "海南市", suburb: "海南" },
      { city: "橋本市", suburb: "橋本" },
      { city: "有田市", suburb: "有田" },
      { city: "御坊市", suburb: "御坊" },
      { city: "田辺市", suburb: "田辺" },
      { city: "新宮市", suburb: "新宮" },
      { city: "紀の川市", suburb: "紀の川" },
      { city: "岩出市", suburb: "岩出" },
      { city: "かつらぎ市", suburb: "かつらぎ" },
    ],
    鳥取県: [
      { city: "鳥取市", suburb: "鳥取" },
      { city: "米子市", suburb: "米子" },
      { city: "倉吉市", suburb: "倉吉" },
      { city: "境港市", suburb: "境港" },
      { city: "岩美町", suburb: "岩美" },
      { city: "若桜町", suburb: "若桜" },
      { city: "智頭町", suburb: "智頭" },
      { city: "八頭町", suburb: "八頭" },
      { city: "三朝町", suburb: "三朝" },
      { city: "湯梨浜町", suburb: "湯梨浜" },
    ],
    島根県: [
      { city: "松江市", suburb: "松江" },
      { city: "浜田市", suburb: "浜田" },
      { city: "出雲市", suburb: "出雲" },
      { city: "益田市", suburb: "益田" },
      { city: "大田市", suburb: "大田" },
      { city: "安来市", suburb: "安来" },
      { city: "江津市", suburb: "江津" },
      { city: "雲南市", suburb: "雲南" },
      { city: "奥出雲町", suburb: "奥出雲" },
      { city: "飯南町", suburb: "飯南" },
    ],
    岡山県: [
      { city: "岡山市", suburb: "岡山" },
      { city: "倉敷市", suburb: "倉敷" },
      { city: "津山市", suburb: "津山" },
      { city: "玉野市", suburb: "玉野" },
      { city: "笠岡市", suburb: "笠岡" },
      { city: "井原市", suburb: "井原" },
      { city: "総社市", suburb: "総社" },
      { city: "高梁市", suburb: "高梁" },
      { city: "新見市", suburb: "新見" },
      { city: "備前市", suburb: "備前" },
    ],
    広島県: [
      { city: "広島市", suburb: "広島" },
      { city: "呉市", suburb: "呉" },
      { city: "竹原市", suburb: "竹原" },
      { city: "三原市", suburb: "三原" },
      { city: "尾道市", suburb: "尾道" },
      { city: "福山市", suburb: "福山" },
      { city: "府中市", suburb: "府中" },
      { city: "三次市", suburb: "三次" },
      { city: "庄原市", suburb: "庄原" },
      { city: "大竹市", suburb: "大竹" },
    ],
    山口県: [
      { city: "下関市", suburb: "下関" },
      { city: "宇部市", suburb: "宇部" },
      { city: "山口市", suburb: "山口" },
      { city: "萩市", suburb: "萩" },
      { city: "防府市", suburb: "防府" },
      { city: "下松市", suburb: "下松" },
      { city: "岩国市", suburb: "岩国" },
      { city: "光市", suburb: "光" },
      { city: "長門市", suburb: "長門" },
      { city: "柳井市", suburb: "柳井" },
    ],
    徳島県: [
      { city: "徳島市", suburb: "徳島" },
      { city: "鳴門市", suburb: "鳴門" },
      { city: "小松島市", suburb: "小松島" },
      { city: "阿南市", suburb: "阿南" },
      { city: "吉野川市", suburb: "吉野川" },
      { city: "阿波市", suburb: "阿波" },
      { city: "美馬市", suburb: "美馬" },
      { city: "三好市", suburb: "三好" },
      { city: "勝浦町", suburb: "勝浦" },
      { city: "上勝町", suburb: "上勝" },
    ],
    香川県: [
      { city: "高松市", suburb: "高松" },
      { city: "丸亀市", suburb: "丸亀" },
      { city: "坂出市", suburb: "坂出" },
      { city: "善通寺市", suburb: "善通寺" },
      { city: "観音寺市", suburb: "観音寺" },
      { city: "さぬき市", suburb: "さぬき" },
      { city: "東かがわ市", suburb: "東かがわ" },
      { city: "三豊市", suburb: "三豊" },
      { city: "土庄町", suburb: "土庄" },
      { city: "小豆島町", suburb: "小豆島" },
    ],
    愛媛県: [
      { city: "松山市", suburb: "松山" },
      { city: "今治市", suburb: "今治" },
      { city: "宇和島市", suburb: "宇和島" },
      { city: "八幡浜市", suburb: "八幡浜" },
      { city: "新居浜市", suburb: "新居浜" },
      { city: "西条市", suburb: "西条" },
      { city: "大洲市", suburb: "大洲" },
      { city: "伊予市", suburb: "伊予" },
      { city: "四国中央市", suburb: "四国中央" },
      { city: "西予市", suburb: "西予" },
    ],
    高知県: [
      { city: "高知市", suburb: "高知" },
      { city: "室戸市", suburb: "室戸" },
      { city: "安芸市", suburb: "安芸" },
      { city: "南国市", suburb: "南国" },
      { city: "土佐市", suburb: "土佐" },
      { city: "須崎市", suburb: "須崎" },
      { city: "宿毛市", suburb: "宿毛" },
      { city: "土佐清水市", suburb: "土佐清水" },
      { city: "四万十市", suburb: "四万十" },
      { city: "香南市", suburb: "香南" },
    ],
    福岡県: [
      { city: "福岡市", suburb: "福岡" },
      { city: "北九州市", suburb: "北九州" },
      { city: "大牟田市", suburb: "大牟田" },
      { city: "久留米市", suburb: "久留米" },
      { city: "直方市", suburb: "直方" },
      { city: "飯塚市", suburb: "飯塚" },
      { city: "田川市", suburb: "田川" },
      { city: "柳川市", suburb: "柳川" },
      { city: "八女市", suburb: "八女" },
      { city: "筑後市", suburb: "筑後" },
    ],
    佐賀県: [
      { city: "佐賀市", suburb: "佐賀" },
      { city: "唐津市", suburb: "唐津" },
      { city: "鳥栖市", suburb: "鳥栖" },
      { city: "多久市", suburb: "多久" },
      { city: "伊万里市", suburb: "伊万里" },
      { city: "武雄市", suburb: "武雄" },
      { city: "鹿島市", suburb: "鹿島" },
      { city: "小城市", suburb: "小城" },
      { city: "嬉野市", suburb: "嬉野" },
      { city: "神埼市", suburb: "神埼" },
    ],
    長崎県: [
      { city: "長崎市", suburb: "長崎" },
      { city: "佐世保市", suburb: "佐世保" },
      { city: "島原市", suburb: "島原" },
      { city: "諫早市", suburb: "諫早" },
      { city: "大村市", suburb: "大村" },
      { city: "平戸市", suburb: "平戸" },
      { city: "松浦市", suburb: "松浦" },
      { city: "対馬市", suburb: "対馬" },
      { city: "壱岐市", suburb: "壱岐" },
      { city: "五島市", suburb: "五島" },
    ],
    熊本県: [
      { city: "熊本市", suburb: "熊本" },
      { city: "八代市", suburb: "八代" },
      { city: "人吉市", suburb: "人吉" },
      { city: "荒尾市", suburb: "荒尾" },
      { city: "水俣市", suburb: "水俣" },
      { city: "玉名市", suburb: "玉名" },
      { city: "山鹿市", suburb: "山鹿" },
      { city: "菊池市", suburb: "菊池" },
      { city: "宇土市", suburb: "宇土" },
      { city: "上天草市", suburb: "上天草" },
    ],
    大分県: [
      { city: "大分市", suburb: "大分" },
      { city: "別府市", suburb: "別府" },
      { city: "中津市", suburb: "中津" },
      { city: "日田市", suburb: "日田" },
      { city: "佐伯市", suburb: "佐伯" },
      { city: "臼杵市", suburb: "臼杵" },
      { city: "津久見市", suburb: "津久見" },
      { city: "竹田市", suburb: "竹田" },
      { city: "豊後高田市", suburb: "豊後高田" },
      { city: "杵築市", suburb: "杵築" },
    ],
    宮崎県: [
      { city: "宮崎市", suburb: "宮崎" },
      { city: "都城市", suburb: "都城" },
      { city: "延岡市", suburb: "延岡" },
      { city: "日南市", suburb: "日南" },
      { city: "小林市", suburb: "小林" },
      { city: "日向市", suburb: "日向" },
      { city: "串間市", suburb: "串間" },
      { city: "西都市", suburb: "西都" },
      { city: "えびの市", suburb: "えびの" },
      { city: "三股町", suburb: "三股" },
    ],
    鹿児島県: [
      { city: "鹿児島市", suburb: "鹿児島" },
      { city: "鹿屋市", suburb: "鹿屋" },
      { city: "枕崎市", suburb: "枕崎" },
      { city: "阿久根市", suburb: "阿久根" },
      { city: "出水市", suburb: "出水" },
      { city: "指宿市", suburb: "指宿" },
      { city: "西之表市", suburb: "西之表" },
      { city: "垂水市", suburb: "垂水" },
      { city: "薩摩川内市", suburb: "薩摩川内" },
      { city: "日置市", suburb: "日置" },
    ],
    沖縄県: [
      { city: "那覇市", suburb: "那覇" },
      { city: "宜野湾市", suburb: "宜野湾" },
      { city: "石垣市", suburb: "石垣" },
      { city: "浦添市", suburb: "浦添" },
      { city: "名護市", suburb: "名護" },
      { city: "糸満市", suburb: "糸満" },
      { city: "沖縄市", suburb: "沖縄" },
      { city: "豊見城市", suburb: "豊見城" },
      { city: "うるま市", suburb: "うるま" },
      { city: "宮古島市", suburb: "宮古島" },
    ],
  };

  return defaultCities[prefecture] || [];
}
